// 安全包裝 Electron preload；非 Electron（瀏覽器預覽）時提供 no-op 回退。
const noop = () => {}
const off = () => noop
const asyncNull = async () => null

export const ov = window.overlay || {
  isElectron: false,
  stateGet: asyncNull,
  stateSet: noop,
  onStateChanged: off,
  setSize: noop,
  getBounds: asyncNull,
  capturePill: asyncNull,
  setPosition: noop,
  setIgnoreMouse: noop,
  popupMenu: noop,
  openConsole: noop,
  closeConsole: noop,
  onConsoleVisibility: off,
  console: {
    requestClose: noop,
    closeWith: async () => ({ ok: false }),
    showPill: async () => ({ ok: false }),
    hideToTray: async () => ({ ok: false }),
    onCloseRequested: off,
  },
  quit: noop,
  onTogglePlay: off,
  onDesktopFrame: off,
  onNpInfo: off,
  npSetFollow: noop,
  ncmRelaunchDebug: async () => ({ ok: false }),
  player: {
    load: async () => ({ ok: false, error: '僅在 App 內可用' }),
    play: async () => ({ ok: false }),
    pause: async () => ({ ok: false }),
    toggle: async () => ({ ok: false }),
    seek: async () => ({ ok: false }),
    setVolume: async () => ({ ok: false }),
    qaLoad: async () => ({ ok: false }),
    qaCommand: async () => ({ ok: false }),
    snapshot: async () => ({ enabled: false, playing: false }),
    onChanged: off,
    onTick: off,
    onSpectrum: off,
    onCommand: off,
    report: noop,
  },
  updates: {
    snapshot: async () => ({ mode: 'disabled', status: 'disabled', currentVersion: 'dev', reason: '僅在 App 內可用' }),
    check: async () => ({ ok: false }),
    download: async () => ({ ok: false }),
    install: async () => ({ ok: false }),
    setSettings: async () => ({ ok: false }),
    onChanged: off,
  },
  privacy: {
    summary: async () => ({ accountStored: false, libraryStored: false, settingsStored: false }),
    erase: async () => ({ ok: false, error: '僅在 App 內可用' }),
  },
  room: {
    host: async () => ({ ok: false }),
    join: async () => ({ ok: false }),
    leave: noop,
    setState: noop,
    tick: noop,
    qaState: noop,
    qaTick: noop,
    snapshot: async () => ({ mode: null, members: [], state: null, ip: '127.0.0.1' }),
    lanIp: async () => '127.0.0.1',
    offerStyle: async () => ({ ok: false }),
    respondStyleOffer: async () => ({ ok: false }),
    pendingOffers: async () => [],
    command: async () => ({ ok: false }),
    setCapabilities: async () => ({ ok: false }),
    onState: off,
    onTick: off,
    onMembers: off,
    onStatus: off,
    onStyleOffer: off,
    onStyleResponse: off,
    onStyleOfferHandled: off,
    onQueue: off,
    onCapabilities: off,
    onCommandResult: off,
  },
  netease: {
    search: async () => ({ ok: false, error: '僅在 App 內可用' }),
    lyric: async () => ({ ok: false }),
    loginQr: async () => ({ ok: false, error: '僅在 App 內可用' }),
    loginCheck: async () => ({ ok: false }),
    loginStatus: async () => ({ ok: false, profile: null }),
    logout: async () => ({ ok: false }),
    userPlaylists: async () => ({ ok: false, data: [] }),
    playlistTracks: async () => ({ ok: false, data: [] }),
  },
  localPlaylists: {
    list: async () => ({ ok: false, data: [] }),
    create: async () => ({ ok: false }),
    rename: async () => ({ ok: false }),
    delete: async () => ({ ok: false }),
    items: async () => ({ ok: false, data: [] }),
    add: async () => ({ ok: false }),
    remove: async () => ({ ok: false }),
    move: async () => ({ ok: false }),
  },
}
